// Code generated by goyacc -o parser.go parser.go.y. DO NOT EDIT.

//line parser.go.y:2
package gojqparser

import __yyfmt__ "fmt"

//line parser.go.y:2

func reverseFuncDef(xs []*FuncDef) []*FuncDef {
	for i, j := 0, len(xs)-1; i < j; i, j = i+1, j-1 {
		xs[i], xs[j] = xs[j], xs[i]
	}
	return xs
}

func prependFuncDef(xs []*FuncDef, x *FuncDef) []*FuncDef {
	xs = append(xs, nil)
	copy(xs[1:], xs)
	xs[0] = x
	return xs
}

//line parser.go.y:19
type yySymType struct {
	yys      int
	value    any
	token    *Token
	operator Operator
}

const tokAltOp = 57346
const tokUpdateOp = 57347
const tokDestAltOp = 57348
const tokCompareOp = 57349
const tokOrOp = 57350
const tokAndOp = 57351
const tokModule = 57352
const tokImport = 57353
const tokInclude = 57354
const tokDef = 57355
const tokAs = 57356
const tokLabel = 57357
const tokBreak = 57358
const tokNull = 57359
const tokTrue = 57360
const tokFalse = 57361
const tokIf = 57362
const tokThen = 57363
const tokElif = 57364
const tokElse = 57365
const tokEnd = 57366
const tokTry = 57367
const tokCatch = 57368
const tokReduce = 57369
const tokForeach = 57370
const tokIdent = 57371
const tokVariable = 57372
const tokModuleIdent = 57373
const tokModuleVariable = 57374
const tokRecurse = 57375
const tokIndex = 57376
const tokNumber = 57377
const tokFormat = 57378
const tokString = 57379
const tokStringStart = 57380
const tokStringQuery = 57381
const tokStringEnd = 57382
const tokInvalid = 57383
const tokInvalidEscapeSequence = 57384
const tokUnterminatedString = 57385
const tokFuncDefQuery = 57386
const tokExpr = 57387
const tokTerm = 57388
const tokEmptyCatch = 57389

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"tokAltOp",
	"tokUpdateOp",
	"tokDestAltOp",
	"tokCompareOp",
	"tokOrOp",
	"tokAndOp",
	"tokModule",
	"tokImport",
	"tokInclude",
	"tokDef",
	"tokAs",
	"tokLabel",
	"tokBreak",
	"tokNull",
	"tokTrue",
	"tokFalse",
	"tokIf",
	"tokThen",
	"tokElif",
	"tokElse",
	"tokEnd",
	"tokTry",
	"tokCatch",
	"tokReduce",
	"tokForeach",
	"tokIdent",
	"tokVariable",
	"tokModuleIdent",
	"tokModuleVariable",
	"tokRecurse",
	"tokIndex",
	"tokNumber",
	"tokFormat",
	"tokString",
	"tokStringStart",
	"tokStringQuery",
	"tokStringEnd",
	"tokInvalid",
	"tokInvalidEscapeSequence",
	"tokUnterminatedString",
	"tokFuncDefQuery",
	"tokExpr",
	"tokTerm",
	"'|'",
	"','",
	"'+'",
	"'-'",
	"'*'",
	"'/'",
	"'%'",
	"'.'",
	"'?'",
	"tokEmptyCatch",
	"'['",
	"';'",
	"':'",
	"'('",
	"')'",
	"']'",
	"'{'",
	"'}'",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line parser.go.y:675

//line yacctab:1
var yyExca = [...]int16{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 142,
	5, 0,
	-2, 30,
	-1, 145,
	7, 0,
	-2, 33,
	-1, 197,
	59, 117,
	-2, 52,
}

const yyPrivate = 57344

const yyLast = 784

var yyAct = [...]int16{
	79, 132, 177, 198, 106, 10, 213, 193, 178, 133,
	138, 32, 5, 74, 105, 111, 48, 182, 183, 184,
	6, 246, 50, 245, 230, 96, 74, 102, 113, 161,
	101, 74, 15, 126, 118, 180, 134, 181, 107, 123,
	229, 249, 135, 117, 100, 160, 73, 75, 74, 125,
	267, 74, 182, 183, 184, 248, 74, 185, 207, 73,
	75, 206, 222, 6, 73, 75, 228, 119, 120, 121,
	180, 255, 181, 284, 130, 282, 136, 201, 281, 74,
	227, 73, 75, 256, 73, 75, 139, 243, 237, 73,
	75, 236, 185, 77, 210, 74, 258, 209, 6, 240,
	156, 74, 232, 159, 165, 151, 152, 231, 163, 164,
	154, 162, 73, 75, 141, 142, 143, 144, 145, 146,
	147, 148, 149, 150, 153, 129, 280, 74, 73, 75,
	74, 186, 187, 128, 73, 75, 191, 43, 44, 275,
	194, 202, 50, 176, 127, 74, 45, 195, 254, 88,
	89, 90, 203, 189, 242, 140, 205, 99, 208, 76,
	73, 75, 122, 73, 75, 80, 74, 217, 199, 200,
	215, 219, 220, 107, 247, 221, 212, 216, 73, 75,
	81, 82, 95, 85, 83, 84, 168, 74, 224, 225,
	170, 226, 171, 269, 188, 214, 214, 233, 74, 73,
	75, 218, 98, 97, 137, 99, 74, 139, 239, 234,
	273, 241, 3, 81, 82, 91, 85, 83, 84, 25,
	73, 75, 74, 169, 24, 86, 87, 88, 89, 90,
	250, 272, 223, 252, 253, 194, 179, 74, 251, 73,
	75, 257, 195, 47, 276, 104, 264, 265, 167, 259,
	260, 173, 266, 174, 172, 73, 75, 268, 86, 87,
	88, 89, 90, 270, 271, 85, 235, 84, 261, 274,
	73, 75, 244, 277, 278, 214, 214, 279, 85, 83,
	84, 43, 44, 283, 52, 53, 54, 55, 56, 57,
	58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
	68, 69, 70, 71, 72, 109, 110, 86, 87, 88,
	89, 90, 158, 43, 44, 86, 87, 88, 89, 90,
	86, 87, 88, 89, 90, 262, 263, 16, 124, 14,
	37, 21, 22, 23, 33, 192, 108, 190, 131, 34,
	211, 35, 36, 39, 41, 40, 42, 19, 20, 28,
	31, 43, 44, 204, 7, 9, 81, 82, 8, 85,
	83, 84, 4, 29, 30, 92, 93, 85, 18, 78,
	2, 27, 94, 157, 38, 1, 155, 26, 52, 53,
	54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
	64, 65, 66, 67, 68, 69, 70, 71, 72, 109,
	110, 86, 87, 88, 89, 90, 0, 43, 44, 86,
	87, 88, 89, 90, 0, 74, 0, 0, 0, 11,
	12, 16, 166, 14, 37, 21, 22, 23, 33, 17,
	108, 0, 0, 34, 103, 35, 36, 39, 41, 40,
	42, 19, 20, 28, 31, 43, 44, 114, 73, 75,
	0, 0, 13, 0, 0, 0, 0, 29, 30, 115,
	116, 13, 18, 0, 0, 27, 0, 0, 38, 0,
	16, 26, 14, 37, 21, 22, 23, 33, 0, 0,
	0, 0, 34, 0, 35, 36, 39, 41, 40, 42,
	19, 20, 28, 31, 43, 44, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 29, 30, 0, 0,
	0, 18, 0, 0, 27, 0, 0, 38, 0, 238,
	26, 16, 0, 14, 37, 21, 22, 23, 33, 0,
	0, 0, 0, 34, 0, 35, 36, 39, 41, 40,
	42, 19, 20, 28, 31, 43, 44, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 29, 30, 0,
	0, 0, 18, 0, 0, 27, 0, 0, 38, 0,
	112, 26, 16, 0, 14, 37, 21, 22, 23, 33,
	0, 0, 0, 0, 34, 0, 35, 36, 39, 41,
	40, 42, 19, 20, 28, 31, 43, 44, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 29, 30,
	0, 0, 0, 18, 0, 0, 27, 0, 0, 38,
	0, 0, 26, 52, 53, 54, 55, 56, 57, 58,
	59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
	69, 70, 71, 72, 49, 0, 0, 0, 0, 0,
	0, 0, 51, 52, 53, 54, 55, 56, 57, 58,
	59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
	69, 70, 71, 72, 49, 0, 0, 0, 0, 175,
	0, 0, 51, 37, 21, 22, 23, 33, 0, 0,
	0, 0, 34, 0, 35, 36, 39, 41, 40, 42,
	19, 20, 28, 31, 43, 44, 0, 0, 0, 46,
	0, 0, 0, 0, 0, 0, 29, 30, 0, 0,
	0, 18, 0, 0, 27, 0, 0, 38, 0, 0,
	26, 52, 53, 54, 55, 56, 57, 58, 59, 60,
	61, 62, 63, 64, 65, 66, 67, 68, 69, 70,
	71, 72, 109, 197, 0, 0, 0, 0, 0, 0,
	43, 44, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 196,
}

var yyPact = [...]int16{
	202, -1000, -1000, -43, 408, 88, 645, -1000, -1000, -1000,
	192, 122, 56, 559, 135, 352, 336, 148, 100, -1000,
	-1000, -1000, -1000, -1000, -33, -1000, 370, 508, -1000, 667,
	667, 244, -1000, 559, 667, 667, 667, 132, 559, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -15, -1000, 85,
	74, 66, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, 559, -21, 559, 190, -43, -1000, 192,
	108, 667, 667, 667, 667, 667, 667, 667, 667, 667,
	667, 46, -1000, -1000, -1000, -1000, -1000, -1000, 100, 314,
	-1000, -1000, 559, -1000, -19, -1000, 52, 49, 559, -1000,
	-1000, -1000, -1000, 42, 559, 148, 148, -1000, 401, 160,
	209, 176, -1000, 131, 214, -1000, 615, 35, 35, 35,
	192, 147, -1000, -1000, -21, 723, 184, 139, 19, -1000,
	559, 352, 271, 258, 360, 266, 98, 98, -1000, -1000,
	-1000, 559, 139, -1000, -1000, -1000, -1, 559, 36, 192,
	-1000, 276, 667, 667, 116, -1000, 559, -1000, 667, -21,
	-21, -1000, -1000, -1000, 559, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, 0, -1000, -1000, 559, -21,
	18, -1000, -24, -1000, 48, 43, 559, -1000, -43, -1000,
	-1000, -1000, 192, 208, 30, -1000, -1000, 457, 37, -1000,
	559, -1000, -1000, 107, 352, 107, 28, 192, -1000, -37,
	-39, 113, -1000, -7, -1000, 192, -1000, -1000, -21, -1000,
	723, -21, -21, 87, 13, -1000, 24, 139, -1000, 34,
	-1000, 192, 667, 667, 303, 559, 559, -1000, -1000, 35,
	-1000, -1000, -1000, -1000, -9, -1000, 559, -1000, -1000, 107,
	107, 169, 559, 559, 173, 152, -1000, -21, 81, -1000,
	223, 192, 559, 559, -1000, -1000, 559, 65, 17, 192,
	-1000, -1000, 559, 12, -1000,
}

var yyPgo = [...]int16{
	0, 375, 370, 362, 358, 10, 354, 355, 447, 353,
	0, 338, 1, 337, 335, 7, 32, 429, 11, 328,
	25, 312, 272, 268, 248, 245, 14, 6, 2, 8,
	243, 16, 236, 232, 3, 224, 219, 15, 4, 215,
}

var yyR1 = [...]int8{
	0, 1, 2, 2, 3, 3, 4, 4, 5, 5,
	6, 6, 7, 7, 8, 8, 9, 9, 34, 34,
	39, 39, 39, 10, 10, 10, 10, 10, 10, 16,
	16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
	11, 11, 12, 12, 12, 13, 13, 14, 14, 15,
	15, 15, 15, 17, 17, 17, 17, 17, 17, 17,
	17, 17, 17, 17, 17, 17, 17, 17, 17, 17,
	17, 17, 17, 17, 17, 17, 17, 17, 17, 17,
	17, 17, 17, 17, 17, 17, 17, 18, 18, 19,
	19, 19, 35, 35, 36, 36, 20, 20, 20, 20,
	20, 21, 21, 22, 22, 23, 23, 24, 24, 25,
	25, 26, 26, 26, 26, 26, 38, 38, 38, 27,
	27, 28, 28, 28, 28, 28, 28, 28, 29, 29,
	29, 30, 30, 31, 31, 31, 32, 32, 33, 33,
	37, 37, 37, 37, 37, 37, 37, 37, 37, 37,
	37, 37, 37, 37, 37, 37, 37, 37, 37, 37,
	37,
}

var yyR2 = [...]int8{
	0, 3, 0, 3, 0, 2, 6, 4, 0, 1,
	1, 1, 0, 2, 5, 8, 1, 3, 1, 1,
	1, 1, 1, 2, 3, 5, 4, 3, 1, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 1,
	1, 3, 1, 3, 3, 1, 3, 1, 3, 3,
	3, 5, 1, 1, 1, 1, 2, 2, 1, 1,
	1, 1, 4, 1, 2, 3, 4, 2, 3, 1,
	2, 2, 1, 2, 1, 7, 3, 9, 9, 11,
	2, 3, 2, 2, 2, 3, 3, 1, 3, 0,
	2, 4, 1, 1, 1, 1, 2, 3, 4, 4,
	5, 1, 3, 0, 5, 0, 2, 0, 2, 1,
	3, 3, 3, 5, 1, 1, 1, 1, 1, 3,
	1, 1, 1, 1, 1, 1, 1, 1, 2, 3,
	4, 1, 3, 3, 3, 3, 2, 3, 1, 3,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1,
}

var yyChk = [...]int16{
	-1000, -1, -2, 10, -3, -29, 63, -6, -4, -7,
	-10, 11, 12, -8, 15, -16, 13, -17, 54, 33,
	34, 17, 18, 19, -35, -36, 63, 57, 35, 49,
	50, 36, -18, 20, 25, 27, 28, 16, 60, 29,
	31, 30, 32, 37, 38, 58, 64, -30, -31, 29,
	-37, 37, 8, 9, 10, 11, 12, 13, 14, 15,
	16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
	26, 27, 28, 47, 14, 48, 37, 37, -7, -10,
	30, 4, 5, 8, 9, 7, 49, 50, 51, 52,
	53, -39, 29, 30, 36, 34, -20, 55, 54, 57,
	-20, -18, 60, 64, -25, -26, -38, -18, 60, 29,
	30, -37, 62, -10, -8, -17, -17, -18, -10, -16,
	-16, -16, 30, -10, -19, 64, 48, 59, 59, 59,
	-10, -11, -12, 30, 57, 63, -10, 14, -5, -29,
	47, -16, -16, -16, -16, -16, -16, -16, -16, -16,
	-16, 59, 60, -20, -18, 62, -10, 59, -21, -10,
	64, 48, 59, 59, -10, 62, 21, -24, 26, 14,
	14, 61, 40, 37, 39, 64, -31, -28, -29, -32,
	35, 37, 17, 18, 19, 57, -28, -28, 47, 6,
	-13, -12, -14, -15, -38, -18, 60, 30, -34, 29,
	30, 58, -10, -10, -9, -34, 62, 59, -10, 61,
	58, 64, -26, -27, -16, -27, 61, -10, -16, -12,
	-12, -10, 62, -33, -28, -10, -12, 62, 48, 64,
	48, 59, 59, -10, -5, 58, 61, 58, 62, -10,
	62, -10, 47, 59, -22, 60, 60, 61, 62, 48,
	-12, -15, -12, -12, 61, 58, 59, -34, 62, -27,
	-27, -23, 22, 23, -10, -10, -28, 59, -10, 24,
	-10, -10, 58, 58, -12, 58, 21, -10, -10, -10,
	61, 61, 58, -10, 61,
}

var yyDef = [...]int16{
	2, -2, 4, 0, 12, 0, 0, 1, 5, 10,
	11, 0, 0, 12, 0, 28, 0, 39, 53, 54,
	55, 58, 59, 60, 61, 63, 0, 0, 69, 0,
	0, 72, 74, 0, 0, 0, 0, 0, 0, 92,
	93, 94, 95, 87, 89, 3, 128, 0, 131, 0,
	0, 0, 140, 141, 142, 143, 144, 145, 146, 147,
	148, 149, 150, 151, 152, 153, 154, 155, 156, 157,
	158, 159, 160, 0, 0, 0, 0, 8, 13, 23,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 20, 21, 22, 82, 83, 84, 0, 0,
	56, 57, 0, 64, 0, 109, 114, 115, 0, 116,
	117, 118, 67, 0, 0, 70, 71, 73, 0, 107,
	0, 0, 80, 0, 0, 129, 0, 0, 0, 0,
	24, 0, 40, 42, 0, 0, 27, 0, 0, 9,
	0, 29, -2, 31, 32, -2, 34, 35, 36, 37,
	38, 0, 0, 85, 86, 96, 0, 0, 0, 101,
	65, 0, 0, 0, 0, 68, 0, 76, 0, 0,
	0, 81, 88, 90, 0, 130, 132, 133, 121, 122,
	123, 124, 125, 126, 127, 0, 134, 135, 0, 0,
	0, 45, 0, 47, 0, 0, 0, -2, 8, 18,
	19, 7, 26, 0, 0, 16, 97, 0, 0, 62,
	0, 66, 110, 111, 120, 112, 0, 103, 108, 0,
	0, 0, 136, 0, 138, 25, 41, 43, 0, 44,
	0, 0, 0, 0, 0, 14, 0, 0, 98, 0,
	99, 102, 0, 0, 105, 0, 0, 91, 137, 0,
	46, 48, 49, 50, 0, 6, 0, 17, 100, 119,
	113, 0, 0, 0, 0, 0, 139, 0, 0, 75,
	0, 106, 0, 0, 51, 15, 0, 0, 0, 104,
	77, 78, 0, 0, 79,
}

var yyTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 53, 3, 3,
	60, 61, 51, 49, 48, 50, 54, 52, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 59, 58,
	3, 3, 3, 55, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 57, 3, 62, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 63, 47, 64,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 56,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:59
		{
			query := yyDollar[3].value.(*Query)
			query.Meta = yyDollar[1].value.(*ConstObject)
			query.Imports = yyDollar[2].value.([]*Import)
			yylex.(*lexer).result = query
		}
	case 2:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.go.y:68
		{
			yyVAL.value = (*ConstObject)(nil)
		}
	case 3:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:72
		{
			yyVAL.value = yyDollar[2].value
		}
	case 4:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.go.y:78
		{
			yyVAL.value = []*Import(nil)
		}
	case 5:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:82
		{
			yyVAL.value = append(yyDollar[1].value.([]*Import), yyDollar[2].value.(*Import))
		}
	case 6:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser.go.y:88
		{
			yyVAL.value = &Import{ImportPath: yyDollar[2].token, ImportAlias: yyDollar[4].token, Meta: yyDollar[5].value.(*ConstObject)}
		}
	case 7:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:92
		{
			yyVAL.value = &Import{IncludePath: yyDollar[2].token, Meta: yyDollar[3].value.(*ConstObject)}
		}
	case 8:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.go.y:98
		{
			yyVAL.value = (*ConstObject)(nil)
		}
	case 10:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:105
		{
			yyVAL.value = &Query{FuncDefs: reverseFuncDef(yyDollar[1].value.([]*FuncDef))}
		}
	case 12:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.go.y:112
		{
			yyVAL.value = []*FuncDef(nil)
		}
	case 13:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:116
		{
			yyVAL.value = append(yyDollar[2].value.([]*FuncDef), yyDollar[1].value.(*FuncDef))
		}
	case 14:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:122
		{
			yyVAL.value = &FuncDef{Name: yyDollar[2].token, Body: yyDollar[4].value.(*Query)}
		}
	case 15:
		yyDollar = yyS[yypt-8 : yypt+1]
//line parser.go.y:126
		{
			yyVAL.value = &FuncDef{yyDollar[2].token, yyDollar[4].value.([]*Token), yyDollar[7].value.(*Query)}
		}
	case 16:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:132
		{
			yyVAL.value = []*Token{yyDollar[1].token}
		}
	case 17:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:136
		{
			yyVAL.value = append(yyDollar[1].value.([]*Token), yyDollar[3].token)
		}
	case 23:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:151
		{
			query := yyDollar[2].value.(*Query)
			query.FuncDefs = prependFuncDef(query.FuncDefs, yyDollar[1].value.(*FuncDef))
			yyVAL.value = query
		}
	case 24:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:157
		{
			yyVAL.value = &Query{Left: yyDollar[1].value.(*Query), Op: OpPipe, Right: yyDollar[3].value.(*Query)}
		}
	case 25:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:161
		{
			yyVAL.value = &Query{Left: yyDollar[1].value.(*Query), Op: OpPipe, Right: yyDollar[5].value.(*Query), Patterns: yyDollar[3].value.([]*Pattern)}
		}
	case 26:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:165
		{
			yyVAL.value = &Query{Term: &Term{Type: TermTypeLabel, Label: &Label{yyDollar[2].token, yyDollar[4].value.(*Query)}}}
		}
	case 27:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:169
		{
			yyVAL.value = &Query{Left: yyDollar[1].value.(*Query), Op: OpComma, Right: yyDollar[3].value.(*Query)}
		}
	case 29:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:176
		{
			yyVAL.value = &Query{Left: yyDollar[1].value.(*Query), Op: yyDollar[2].operator, Right: yyDollar[3].value.(*Query)}
		}
	case 30:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:180
		{
			yyVAL.value = &Query{Left: yyDollar[1].value.(*Query), Op: yyDollar[2].operator, Right: yyDollar[3].value.(*Query)}
		}
	case 31:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:184
		{
			yyVAL.value = &Query{Left: yyDollar[1].value.(*Query), Op: OpOr, Right: yyDollar[3].value.(*Query)}
		}
	case 32:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:188
		{
			yyVAL.value = &Query{Left: yyDollar[1].value.(*Query), Op: OpAnd, Right: yyDollar[3].value.(*Query)}
		}
	case 33:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:192
		{
			yyVAL.value = &Query{Left: yyDollar[1].value.(*Query), Op: yyDollar[2].operator, Right: yyDollar[3].value.(*Query)}
		}
	case 34:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:196
		{
			yyVAL.value = &Query{Left: yyDollar[1].value.(*Query), Op: OpAdd, Right: yyDollar[3].value.(*Query)}
		}
	case 35:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:200
		{
			yyVAL.value = &Query{Left: yyDollar[1].value.(*Query), Op: OpSub, Right: yyDollar[3].value.(*Query)}
		}
	case 36:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:204
		{
			yyVAL.value = &Query{Left: yyDollar[1].value.(*Query), Op: OpMul, Right: yyDollar[3].value.(*Query)}
		}
	case 37:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:208
		{
			yyVAL.value = &Query{Left: yyDollar[1].value.(*Query), Op: OpDiv, Right: yyDollar[3].value.(*Query)}
		}
	case 38:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:212
		{
			yyVAL.value = &Query{Left: yyDollar[1].value.(*Query), Op: OpMod, Right: yyDollar[3].value.(*Query)}
		}
	case 39:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:216
		{
			yyVAL.value = &Query{Term: yyDollar[1].value.(*Term)}
		}
	case 40:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:222
		{
			yyVAL.value = []*Pattern{yyDollar[1].value.(*Pattern)}
		}
	case 41:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:226
		{
			yyVAL.value = append(yyDollar[1].value.([]*Pattern), yyDollar[3].value.(*Pattern))
		}
	case 42:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:232
		{
			yyVAL.value = &Pattern{Name: yyDollar[1].token}
		}
	case 43:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:236
		{
			yyVAL.value = &Pattern{Array: yyDollar[2].value.([]*Pattern)}
		}
	case 44:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:240
		{
			yyVAL.value = &Pattern{Object: yyDollar[2].value.([]*PatternObject)}
		}
	case 45:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:246
		{
			yyVAL.value = []*Pattern{yyDollar[1].value.(*Pattern)}
		}
	case 46:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:250
		{
			yyVAL.value = append(yyDollar[1].value.([]*Pattern), yyDollar[3].value.(*Pattern))
		}
	case 47:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:256
		{
			yyVAL.value = []*PatternObject{yyDollar[1].value.(*PatternObject)}
		}
	case 48:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:260
		{
			yyVAL.value = append(yyDollar[1].value.([]*PatternObject), yyDollar[3].value.(*PatternObject))
		}
	case 49:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:266
		{
			yyVAL.value = &PatternObject{Key: yyDollar[1].token, Val: yyDollar[3].value.(*Pattern)}
		}
	case 50:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:270
		{
			yyVAL.value = &PatternObject{KeyString: yyDollar[1].value.(*String), Val: yyDollar[3].value.(*Pattern)}
		}
	case 51:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:274
		{
			yyVAL.value = &PatternObject{KeyQuery: yyDollar[2].value.(*Query), Val: yyDollar[5].value.(*Pattern)}
		}
	case 52:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:278
		{
			yyVAL.value = &PatternObject{Key: yyDollar[1].token}
		}
	case 53:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:284
		{
			yyVAL.value = &Term{Type: TermTypeIdentity}
		}
	case 54:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:288
		{
			yyVAL.value = &Term{Type: TermTypeRecurse}
		}
	case 55:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:292
		{
			yyVAL.value = &Term{Type: TermTypeIndex, Index: &Index{Name: yyDollar[1].token}}
		}
	case 56:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:296
		{
			suffix := yyDollar[2].value.(*Suffix)
			if suffix.Iter {
				yyVAL.value = &Term{Type: TermTypeIdentity, SuffixList: []*Suffix{suffix}}
			} else {
				yyVAL.value = &Term{Type: TermTypeIndex, Index: suffix.Index}
			}
		}
	case 57:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:305
		{
			yyVAL.value = &Term{Type: TermTypeIndex, Index: &Index{Str: yyDollar[2].value.(*String)}}
		}
	case 58:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:309
		{
			yyVAL.value = &Term{Type: TermTypeNull}
		}
	case 59:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:313
		{
			yyVAL.value = &Term{Type: TermTypeTrue}
		}
	case 60:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:317
		{
			yyVAL.value = &Term{Type: TermTypeFalse}
		}
	case 61:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:321
		{
			yyVAL.value = &Term{Type: TermTypeFunc, Func: &Func{Name: yyDollar[1].token}}
		}
	case 62:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:325
		{
			yyVAL.value = &Term{Type: TermTypeFunc, Func: &Func{Name: yyDollar[1].token, Args: yyDollar[3].value.([]*Query)}}
		}
	case 63:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:329
		{
			yyVAL.value = &Term{Type: TermTypeFunc, Func: &Func{Name: yyDollar[1].token}}
		}
	case 64:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:333
		{
			yyVAL.value = &Term{Type: TermTypeObject, Object: &Object{}}
		}
	case 65:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:337
		{
			yyVAL.value = &Term{Type: TermTypeObject, Object: &Object{yyDollar[2].value.([]*ObjectKeyVal)}}
		}
	case 66:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:341
		{
			yyVAL.value = &Term{Type: TermTypeObject, Object: &Object{yyDollar[2].value.([]*ObjectKeyVal)}}
		}
	case 67:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:345
		{
			yyVAL.value = &Term{Type: TermTypeArray, Array: &Array{}}
		}
	case 68:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:349
		{
			yyVAL.value = &Term{Type: TermTypeArray, Array: &Array{yyDollar[2].value.(*Query)}}
		}
	case 69:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:353
		{
			yyVAL.value = &Term{Type: TermTypeNumber, Number: yyDollar[1].token}
		}
	case 70:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:357
		{
			yyVAL.value = &Term{Type: TermTypeUnary, Unary: &Unary{OpAdd, yyDollar[2].value.(*Term)}}
		}
	case 71:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:361
		{
			yyVAL.value = &Term{Type: TermTypeUnary, Unary: &Unary{OpSub, yyDollar[2].value.(*Term)}}
		}
	case 72:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:365
		{
			yyVAL.value = &Term{Type: TermTypeFormat, Format: yyDollar[1].token}
		}
	case 73:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:369
		{
			yyVAL.value = &Term{Type: TermTypeFormat, Format: yyDollar[1].token, Str: yyDollar[2].value.(*String)}
		}
	case 74:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:373
		{
			yyVAL.value = &Term{Type: TermTypeString, Str: yyDollar[1].value.(*String)}
		}
	case 75:
		yyDollar = yyS[yypt-7 : yypt+1]
//line parser.go.y:377
		{
			yyVAL.value = &Term{Type: TermTypeIf, If: &If{yyDollar[2].value.(*Query), yyDollar[4].value.(*Query), yyDollar[5].value.([]*IfElif), yyDollar[6].value.(*Query)}}
		}
	case 76:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:381
		{
			yyVAL.value = &Term{Type: TermTypeTry, Try: &Try{yyDollar[2].value.(*Query), yyDollar[3].value.(*Query)}}
		}
	case 77:
		yyDollar = yyS[yypt-9 : yypt+1]
//line parser.go.y:385
		{
			yyVAL.value = &Term{Type: TermTypeReduce, Reduce: &Reduce{yyDollar[2].value.(*Query), yyDollar[4].value.(*Pattern), yyDollar[6].value.(*Query), yyDollar[8].value.(*Query)}}
		}
	case 78:
		yyDollar = yyS[yypt-9 : yypt+1]
//line parser.go.y:389
		{
			yyVAL.value = &Term{Type: TermTypeForeach, Foreach: &Foreach{yyDollar[2].value.(*Query), yyDollar[4].value.(*Pattern), yyDollar[6].value.(*Query), yyDollar[8].value.(*Query), nil}}
		}
	case 79:
		yyDollar = yyS[yypt-11 : yypt+1]
//line parser.go.y:393
		{
			yyVAL.value = &Term{Type: TermTypeForeach, Foreach: &Foreach{yyDollar[2].value.(*Query), yyDollar[4].value.(*Pattern), yyDollar[6].value.(*Query), yyDollar[8].value.(*Query), yyDollar[10].value.(*Query)}}
		}
	case 80:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:397
		{
			yyVAL.value = &Term{Type: TermTypeBreak, Break: yyDollar[2].token}
		}
	case 81:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:401
		{
			yyVAL.value = &Term{Type: TermTypeQuery, Query: yyDollar[2].value.(*Query)}
		}
	case 82:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:405
		{
			yyDollar[1].value.(*Term).SuffixList = append(yyDollar[1].value.(*Term).SuffixList, &Suffix{Index: &Index{Name: yyDollar[2].token}})
		}
	case 83:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:409
		{
			yyDollar[1].value.(*Term).SuffixList = append(yyDollar[1].value.(*Term).SuffixList, yyDollar[2].value.(*Suffix))
		}
	case 84:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:413
		{
			yyDollar[1].value.(*Term).SuffixList = append(yyDollar[1].value.(*Term).SuffixList, &Suffix{Optional: true})
		}
	case 85:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:417
		{
			yyDollar[1].value.(*Term).SuffixList = append(yyDollar[1].value.(*Term).SuffixList, yyDollar[3].value.(*Suffix))
		}
	case 86:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:421
		{
			yyDollar[1].value.(*Term).SuffixList = append(yyDollar[1].value.(*Term).SuffixList, &Suffix{Index: &Index{Str: yyDollar[3].value.(*String)}})
		}
	case 87:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:427
		{
			yyVAL.value = &String{Str: yyDollar[1].token}
		}
	case 88:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:431
		{
			yyVAL.value = &String{Queries: yyDollar[2].value.([]*Query)}
		}
	case 89:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.go.y:437
		{
			yyVAL.value = []*Query{}
		}
	case 90:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:441
		{
			yyVAL.value = append(yyDollar[1].value.([]*Query), &Query{Term: &Term{Type: TermTypeString, Str: &String{Str: yyDollar[2].token}}})
		}
	case 91:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:445
		{
			yylex.(*lexer).inString = true
			yyVAL.value = append(yyDollar[1].value.([]*Query), &Query{Term: &Term{Type: TermTypeQuery, Query: yyDollar[3].value.(*Query)}})
		}
	case 96:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:460
		{
			yyVAL.value = &Suffix{Iter: true}
		}
	case 97:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:464
		{
			yyVAL.value = &Suffix{Index: &Index{Start: yyDollar[2].value.(*Query)}}
		}
	case 98:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:468
		{
			yyVAL.value = &Suffix{Index: &Index{Start: yyDollar[2].value.(*Query), IsSlice: true}}
		}
	case 99:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:472
		{
			yyVAL.value = &Suffix{Index: &Index{End: yyDollar[3].value.(*Query), IsSlice: true}}
		}
	case 100:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:476
		{
			yyVAL.value = &Suffix{Index: &Index{Start: yyDollar[2].value.(*Query), End: yyDollar[4].value.(*Query), IsSlice: true}}
		}
	case 101:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:482
		{
			yyVAL.value = []*Query{yyDollar[1].value.(*Query)}
		}
	case 102:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:486
		{
			yyVAL.value = append(yyDollar[1].value.([]*Query), yyDollar[3].value.(*Query))
		}
	case 103:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.go.y:492
		{
			yyVAL.value = []*IfElif(nil)
		}
	case 104:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:496
		{
			yyVAL.value = append(yyDollar[1].value.([]*IfElif), &IfElif{yyDollar[3].value.(*Query), yyDollar[5].value.(*Query)})
		}
	case 105:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.go.y:502
		{
			yyVAL.value = (*Query)(nil)
		}
	case 106:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:506
		{
			yyVAL.value = yyDollar[2].value
		}
	case 107:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.go.y:512
		{
			yyVAL.value = (*Query)(nil)
		}
	case 108:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:516
		{
			yyVAL.value = yyDollar[2].value
		}
	case 109:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:522
		{
			yyVAL.value = []*ObjectKeyVal{yyDollar[1].value.(*ObjectKeyVal)}
		}
	case 110:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:526
		{
			yyVAL.value = append(yyDollar[1].value.([]*ObjectKeyVal), yyDollar[3].value.(*ObjectKeyVal))
		}
	case 111:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:532
		{
			yyVAL.value = &ObjectKeyVal{Key: yyDollar[1].token, Val: yyDollar[3].value.(*Query)}
		}
	case 112:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:536
		{
			yyVAL.value = &ObjectKeyVal{KeyString: yyDollar[1].value.(*String), Val: yyDollar[3].value.(*Query)}
		}
	case 113:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.go.y:540
		{
			yyVAL.value = &ObjectKeyVal{KeyQuery: yyDollar[2].value.(*Query), Val: yyDollar[5].value.(*Query)}
		}
	case 114:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:544
		{
			yyVAL.value = &ObjectKeyVal{Key: yyDollar[1].token}
		}
	case 115:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:548
		{
			yyVAL.value = &ObjectKeyVal{KeyString: yyDollar[1].value.(*String)}
		}
	case 119:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:559
		{
			yyVAL.value = &Query{Left: yyDollar[1].value.(*Query), Op: OpPipe, Right: yyDollar[3].value.(*Query)}
		}
	case 121:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:566
		{
			yyVAL.value = &ConstTerm{Object: yyDollar[1].value.(*ConstObject)}
		}
	case 122:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:570
		{
			yyVAL.value = &ConstTerm{Array: yyDollar[1].value.(*ConstArray)}
		}
	case 123:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:574
		{
			yyVAL.value = &ConstTerm{Number: yyDollar[1].token}
		}
	case 124:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:578
		{
			yyVAL.value = &ConstTerm{Str: yyDollar[1].token}
		}
	case 125:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:582
		{
			yyVAL.value = &ConstTerm{Null: true}
		}
	case 126:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:586
		{
			yyVAL.value = &ConstTerm{True: true}
		}
	case 127:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:590
		{
			yyVAL.value = &ConstTerm{False: true}
		}
	case 128:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:596
		{
			yyVAL.value = &ConstObject{}
		}
	case 129:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:600
		{
			yyVAL.value = &ConstObject{yyDollar[2].value.([]*ConstObjectKeyVal)}
		}
	case 130:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.go.y:604
		{
			yyVAL.value = &ConstObject{yyDollar[2].value.([]*ConstObjectKeyVal)}
		}
	case 131:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:610
		{
			yyVAL.value = []*ConstObjectKeyVal{yyDollar[1].value.(*ConstObjectKeyVal)}
		}
	case 132:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:614
		{
			yyVAL.value = append(yyDollar[1].value.([]*ConstObjectKeyVal), yyDollar[3].value.(*ConstObjectKeyVal))
		}
	case 133:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:620
		{
			yyVAL.value = &ConstObjectKeyVal{Key: yyDollar[1].token, Val: yyDollar[3].value.(*ConstTerm)}
		}
	case 134:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:624
		{
			yyVAL.value = &ConstObjectKeyVal{Key: yyDollar[1].token, Val: yyDollar[3].value.(*ConstTerm)}
		}
	case 135:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:628
		{
			yyVAL.value = &ConstObjectKeyVal{KeyString: yyDollar[1].token, Val: yyDollar[3].value.(*ConstTerm)}
		}
	case 136:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.go.y:634
		{
			yyVAL.value = &ConstArray{}
		}
	case 137:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:638
		{
			yyVAL.value = &ConstArray{yyDollar[2].value.([]*ConstTerm)}
		}
	case 138:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.go.y:644
		{
			yyVAL.value = []*ConstTerm{yyDollar[1].value.(*ConstTerm)}
		}
	case 139:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.go.y:648
		{
			yyVAL.value = append(yyDollar[1].value.([]*ConstTerm), yyDollar[3].value.(*ConstTerm))
		}
	}
	goto yystack /* stack new state and value */
}
